version: '3.5'

services:
  frontend:
    image: kurkkumopo-frontend
    ports:
      - 3000:3000
  backend:
    image: kurkkumopo-backend
    volumes:
      - model:/src/model
    ports:
      - 5000:5000
  training:
    image: kurkkumopo-training
    volumes:
      - model:/src/model
      - imgs:/src/imgs
      - data:/src/data
    


volumes:
  model:
  imgs:
  data: