version: '3.5'

services:
    redis:
        image: redis:latest
    frontend:
        image: frontend
        ports:
            - 5000:5000
    backend:
        image: backend
        ports:
            - 8080:8080
        environment:
            REDIS_HOST: redis
